# Generated by Django 3.2.2 on 2021-05-13 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='School',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='records.school'),
            preserve_default=False,
        ),
    ]
